### PR TITLE
Application execution result minnor fix

### PR DESCRIPTION
**Pull request by vncoelho**
Hey @erikzhang,

There is a little problem related to small modification on `ApplicationExecutedEventArgs`, which is not allowing us to compile neo-cli (#176).
The inclusion of `ApplicationExecutionResult[]`

It is something simple to do, but I am not expert in this JSON creation in C#. 
Thus, I tried several times until I reached a compiling version. eahuehauea

What is the best way to create this array with ApplicationExecutionResult values?

### CODE REVIEW

**Comment by erikzhang** [comment]
I will change it to:

```c#
private void LevelDBBlockchain_ApplicationExecuted(object sender, ApplicationExecutedEventArgs e)
{
    JObject json = new JObject();
    json["txid"] = e.Transaction.Hash.ToString();
    json["executions"] = e.ExecutionResults.Select(p =>
    {
        JObject execution = new JObject();
        execution["trigger"] = p.Trigger;
        execution["contract"] = p.ScriptHash.ToString();
        execution["vmstate"] = p.VMState;
        execution["gas_consumed"] = p.GasConsumed.ToString();
        execution["stack"] = p.Stack.Select(q => q.ToParameter().ToJson()).ToArray();
        execution["notifications"] = p.Notifications.Select(q =>
        {
            JObject notification = new JObject();
            notification["contract"] = q.ScriptHash.ToString();
            notification["state"] = q.State.ToParameter().ToJson();
            return notification;
        }).ToArray();
        return execution;
    }).ToArray();
    Directory.CreateDirectory(Settings.Default.Paths.ApplicationLogs);
    string path = Path.Combine(Settings.Default.Paths.ApplicationLogs, $"{e.Transaction.Hash}.json");
    File.WriteAllText(path, json.ToString());
}
```

But there are many things to change. I will do it after neo-project/neo#265 is merged.

**Comment by vncoelho** [comment]
I got a compiling one:

```  
 private void LevelDBBlockchain_ApplicationExecuted(object sender, ApplicationExecutedEventArgs e)
        {
            JObject json = new JObject();
    	    json["txid"] = e.Transaction.Hash.ToString();
            json["executionresults"] = new JArray();
            JArray arrayToAdd = (JArray)json["executionresults"];
    	    for (int i = 0; i < e.ExecutionResults.Length ; i++)
    	    {
                JObject jsonER = new JObject();
                jsonER["vmstate"] = e.ExecutionResults[i].VMState;
                jsonER["gas_consumed"] = e.ExecutionResults[i].GasConsumed.ToString();
                jsonER["stack"] = e.ExecutionResults[i].Stack.Select(p => p.ToParameter().ToJson()).ToArray();
                jsonER["notifications"] = e.ExecutionResults[i].Notifications.Select(p =>
                {
                         JObject notification = new JObject();
                         notification["contract"] = p.ScriptHash.ToString();
                         notification["state"] = p.State.ToParameter().ToJson();
                         return notification;
                }).ToArray();
                arrayToAdd.Add(jsonER);
    	    }
                Directory.CreateDirectory(Settings.Default.Paths.ApplicationLogs);
                string path = Path.Combine(Settings.Default.Paths.ApplicationLogs, $"{e.Transaction.Hash}.json");
                File.WriteAllText(path, json.ToString());
            }
    }
```

**Comment by shargon** [comment]
in what branch are defined 
```
json["vmstate"] = e.VMState;
            json["gas_consumed"] = e.GasConsumed.ToString();
            json["stack"] = e.Stack.Select(p => p.ToParameter().ToJson()).ToArray();
            json["notifications"] = e.Notifications.Select(p =>
```
?

https://github.com/neo-project/neo/blob/master/neo/Implementations/Blockchains/LevelDB/ApplicationExecutedEventArgs.cs

**Comment by vncoelho** [comment]
Hiii, Sharrgons, good to have you here.

Check it here:

https://github.com/neo-project/neo/blob/8e993698494ea861cdc756f4d6f443ee5c51340b/neo/Implementations/Blockchains/LevelDB/ApplicationExecutionResult.cs

**Comment by vncoelho** [comment]
Hi, Erik. Was not needed to iterate over Application Results?

**Comment by erikzhang** [comment]
NEP-7 is removed from v2.7.6 temporarily. So it's better to keep compatibility with v2.7.5

**Comment by vncoelho** [comment]
Thanks, Erik.
Nice version. 
Time for 15s :dagger:

**Pull request closed without merging**
