### PR TITLE
Check dotnet format in travis and adding .editorconfig

### PR DESCRIPTION
**Pull request by vncoelho**

### CODE REVIEW

**Comment by shargon** [comment]
I don't know why we use here docker for travis, for me are different things, i prefer use travis without the docker file

**Comment by vncoelho** [comment]
I agree. 
Lets rethink this.

**Comment by lock9** [comment]
@shargon  any ideas why this PR is being blocked by Travis?

**Comment by shargon** [comment]
because it doesn't have the dotnet framework

**Pull request closed without merging**
