### PR TITLE
Allow users to select storage engine

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by shargon** [comment]
LevelDB will be distributed by default as a plugin in releases?

**Comment by erikzhang** [comment]
All the storage plugins will be included.

**Comment by vncoelho** [comment]
@shargon, perhaps we distribute all as it has been done and keep leveldb as default for now.

**Comment by shargon** [comment]
Require https://github.com/neo-project/neo/pull/1312

**Pull request merged**
