### PR TITLE
Fix import multisigaddress method on solo chain

### PR DESCRIPTION
**Pull request by superboyiii**
Don't need at least 5 elements for the command of import multisigaddress on solo chain.

### CODE REVIEW

**Comment by superboyiii** [comment]
That's your works, hahaha!  [#703](https://github.com/neo-project/neo/issues/703)

**Comment by vncoelho** [comment]
Aehuaheuaheaea, I got it...

I never used the neo-cli for multi-sig. I will build the client and test, then approve it. Maybe it take 1-3 days until I can focus on it, but I will check it out.

If someone could test it before.

**Comment by superboyiii** [comment]
On master branch (NEO3.X), it's already applied on. I just sync it to the latest.

**Comment by superboyiii** [comment]
I've tested it before on NEO3.0.

**Comment by vncoelho** [comment]
Sorry for the delay. Testing it now.

**Comment by vncoelho** [comment]
even the example in the docs is showing error:

https://docs.neo.org/en-us/node/cli/cli.html

`import multisigaddress 1 037ebe29fff57d8c177870e9d9eecb046b27fc290ccbac88a0e3da8bac5daa630d 03b34a4be80db4a38f62bb41d63f9b1cb664e5e0416c1ac39db605a8e30ef270cc
`

**Comment by superboyiii** [comment]
> Updated, it is working, I created a wallet and forgot the extension, then has not actually been created.
> 
> A wallet opened was still missing.
> 
> However, the `error` message should be improved because it was not reporting any wallet open issue.
> It was probably reaching `wallet.Save();` because the default wallet was not NEP6.

Yes, that's correct. We should approve the 'error' message to help developers know the wrong point.

**Pull request merged**
