### PR TITLE
Neo cli daemon with wallet unlock

### PR DESCRIPTION
**Pull request by purplesoft-io**
added --rpcwallet option.
this function allow to unlock a wallet before start neo rpc server.

usage:
dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.db3" "/home/user/passwordfilepath/pass.txt"

dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.json" "/home/user/passwordfilepath/pass.txt"

or with screen (linux)
screen -dmS neod dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.db3" "/home/user/passwordfilepath/pass.txt"

screen -dmS neod dotnet neo-cli.dll --rpcwallet "/home/user/walletpath/wallet.json" "/home/user/passwordfilepath/pass.txt"

tiziano@purplesoft.io

Donations are welcome XD
we are developing NEO WEB PANEL MANAGER for NEO NODES (also private deploy of NEO blockchain).

NEO: AYUd4G2dNXAEyUxkZGyMdXAnJ396jJfNDz
ETC: 0x982e45402ad06d0a01f3e54732b28c76d9870422
BTC: 1HxdgF6WsvcRVNiXhz6jZgbD9eopvzAxap
ETH: 0x5cb3784e71710f681410d30d615a3b3bb3c24ff1

### CODE REVIEW

**Comment by metachris** [comment]
How many critical projects do this is by using environment variables for passwords and keys.

**Comment by purplesoft-io** [comment]
can we read it from file like ethereum?

**Comment by purplesoft-io** [comment]
Hi erik, chris,
load password from file commit just made.
Let me know if can be included in master branch.
Thanks,
Tiz

**Comment by metachris** [comment]
I have no say in this, but generally I think environment variables are more robust and flexible.

**Comment by purplesoft-io** [comment]
Hi Erik,
new changes just commited.
https://github.com/neo-project/neo-cli/pull/152

**Pull request closed without merging**
