### PR TITLE
feat: added getunclaimedgas and claimgas RPC methods.

### PR DESCRIPTION
**Pull request by bmclain**
Exchanges require a method for claiming gas via RPC. 

This PR adds two methods: 

- `getunclaimedgas` which returns the available and unavailable gas.
- `claimgas` which creates a claim TX and relays the tx.

Let me know what you think. It would be great to have this feature in the next release (2.7.7).

### CODE REVIEW

**Comment by bmclain** [comment]
Another potential feature would be to submit an address as a param to `claimgas` to be used as the output for the claim tx.

**Comment by erikzhang** [comment]
This feature can be implemented in plugins. See https://github.com/neo-project/neo/blob/master/neo/Plugins/RpcPlugin.cs

**Comment by bmclain** [comment]
Is it safe to assume that the existing RPC methods are set in stone and no new RPC methods will be added in the future? I only ask because claiming gas and getting the unclaimed amount of gas seem to be core functionality imho. Is there a criteria to decide what should be a plugin and what should be a core RPC call?

**Comment by erikzhang** [comment]
The gas distribution mechanism will be modified in Neo 3.0 and we are not going to accept any relevant pull request before that.
So at present this kind of the features should be implemented in plugins.

**Pull request closed without merging**
