### PR TITLE
Update config files

### PR DESCRIPTION
**Pull request by shargon**
Update config files for https://github.com/neo-project/neo-cli/pull/320

### CODE REVIEW

**Comment by jsolman** [comment]
Since it is the default, you don’t have to add it, maybe add the other new ones as @vncoelho said if you are going to add this.

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-cli/blob/b4afa6d9485f72b1f4387cbd4a173b3419ba7b0f/neo-cli/Settings.cs#L59

It has a default value, and you don't have to add it. It is generally not recommended to modify these parameters.

**Comment by vncoelho** [comment]
Makes sense, @erikzhang. From this perspective, maybe the config would become a little heavy with plenty of information.

**Comment by shargon** [comment]
ok, we can close it

**Pull request closed without merging**
