### PR TITLE
Fix dockerbuild

### PR DESCRIPTION
**Pull request by Ashuaidehao**
Fix(https://github.com/neo-project/neo-cli/issues/412).

### CODE REVIEW

**Comment by Ashuaidehao** [comment]
WeChat Screenshot_20190729174547
Seems the test scripts need to be updated.  The interactive mode of command "create wallet" has changed.

**Comment by Ashuaidehao** [comment]
> Nice job!
> 
> How did you find that? aueahuea

WeChat Image_20190729181510
The previous build alway shows it download the wrong version of "Neo" nuget package,but in my local it's all right . So in the docker it mostly miss some nuget source . 
And can some one help to change the test script ? I'm not familiar with the expect script(https://github.com/neo-project/neo-cli/blob/master/ci/test-neo-cli.expect#L21).

**Comment by vncoelho** [comment]
As @erikzhang said, we can fix that in another PR.

I believe that a next message came. Since it uses expect. everything should be really expected.

An extra line might be needed to be added around here: https://github.com/neo-project/neo-cli/blob/ebff16b867831bfb291bb63c2d41410cd0d36dad/ci/test-neo-cli.expect#L10

**Comment by vncoelho** [comment]
In fact, modify this one here:

https://github.com/neo-project/neo-cli/blob/ebff16b867831bfb291bb63c2d41410cd0d36dad/ci/test-neo-cli.expect#L20-L25

And change it to that phrase that comes, with a `yes` in `{}`

```
send "create wallet test-wallet.json\n"
expect {
    "Warning: xxxx:" { send "yes\n" }
}
```

**Comment by Ashuaidehao** [comment]
https://github.com/neo-project/neo-cli/blob/ebff16b867831bfb291bb63c2d41410cd0d36dad/ci/run-tests-in-docker.sh#L37

This assert seems to be out-of-date now.Can someone provide a new one?
The rpc response is :
` {"jsonrpc":"2.0","id":3,"result":{"script":"00c10b746f74616c537570706c7914f91d6b7085db7c5aaf09f19eeec1ca3c0db2c6ec68627d5b52","state":"FAULT","gas_consumed":"30","stack":[]}}`

**Comment by erikzhang** [comment]
Let's merge this one first, then fix the tests in another PR.

**Pull request merged**
