### PR TITLE
Fix control+c

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-cli/issues/425

### CODE REVIEW

**Comment by vncoelho** [comment]
@shargon, will this handle https://github.com/neo-project/neo-cli/pull/327?

**Comment by shargon** [comment]
Yes, looks the same, but in my fix it exits like a regular "exit"

**Comment by vncoelho** [comment]
@shargon, ctrl+c still did not work here, it just print `^C`

**Comment by shargon** [comment]
Is working for me :S

**Comment by vncoelho** [comment]
image

**Comment by shargon** [comment]
I will close this in favor of https://github.com/neo-project/neo-cli/pull/327

**Pull request closed without merging**
