### PR TITLE
GetAddressBalance rpc call

### PR DESCRIPTION
**Pull request by Pwnmanship**
Added an rpc call in the neo-cli rpc to get balances of all assets grouped in 'confirmed', 'unconfirmed' and 'spendable'.

This makes it easier to see incomming transactions on an address and helps brokers and exchanges who receive coins on an address.

### CODE REVIEW

**Comment by erikzhang** [comment]
Why not just use "getaccountstate"?

**Comment by Pwnmanship** [comment]
@erikzhang because getaccountstate doesn't provide the amount received unconfirmed and confirmed. We like to check how many coins are comming to the address and how many are confirmed.

**Comment by Pwnmanship** [comment]
Unconfirmed = every coin that is not yet confirmed yet
Confirmed = every coin that is already confirmed
Spendable = every coin that is confirmed and hasn't been spend yet (aka the balance you can use)

We mostly use the first one so we can check if we got an incomming transaction.

**Comment by erikzhang** [comment]
Using this way to check for incomming transactions is not accurate and may cause mistakes.
You need to use `getblock` command to look at every transactions in blocks, and check the outputs of transactions for deposit.

**Pull request closed without merging**
