### PR TITLE
v2.9.3

### PR DESCRIPTION
**Pull request by vncoelho**
@erikzhang, fell free to modify the CHANGELOG and other necessary changes (maybe something can be missing).

### CODE REVIEW

**Comment by shargon** [comment]
`-CI00015` why?

**Comment by vncoelho** [comment]
I got it from the plugins opened PR.

**Comment by erikzhang** [comment]
> why -CI00015 ?

This is the Neo daily build version number.

https://www.myget.org/feed/neo/package/nuget/Neo

This is a description of the daily build:

https://github.com/neo-project/neo/blob/master/README.md#daily-builds

Any PR that uses daily build dependencies will not be merged until it is changed to a stable version.

**Comment by vncoelho** [comment]
I had never understood this, now I got the idea. Thanks for the description, @erikzhang.

**Pull request merged**
