### PR TITLE
3.0.0-CI00130

### PR DESCRIPTION
**Pull request by erikzhang**

### CODE REVIEW

**Comment by shargon** [comment]
The rest of the error will come in other PR?

**Comment by erikzhang** [comment]
> Is good to me, still having errors in neo-cli, but step by step

What errors?

**Comment by shargon** [comment]
It doesn't compile to me

**Comment by vncoelho** [comment]
OMG, this guy is a master yoda.

No errors, @erikzhang:

```cs
Step 43/63 : RUN dotnet publish /opt/neoCli/neo-cli/neo-cli.csproj -o neo-cli -c Release -r ubuntu.16.04-x64
 ---> Running in 451cc52612e9
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
Services/ConsoleServiceBase.cs(302,34): warning CS0168: The variable 'ex' is declared but never used [/opt/neoCli/neo-cli/neo-cli.csproj]
  neo-cli -> /opt/neoCli/neo-cli/bin/Release/netcoreapp2.1/ubuntu.16.04-x64/neo-cli.dll
  neo-cli -> /opt/neoCli/neo-cli/neo-cli/
Removing intermediate container 451cc52612e9
 ---> b273a309f635
```

**Comment by vncoelho** [comment]
Compiled with these commits:

```sh
NEO_CLI_BLOCKCHAIN_URL=https://github.com/neo-project/neo-cli.git
NEO_CLI_BRANCH=3.0/neo-122
NEO_CLI_COMMIT=d19206bc743c71fdc81644bf7f88143fab744fa3
NEO_BLOCKCHAIN_URL=https://github.com/neo-project/neo.git
NEO_BLOCKCHAIN_BRANCH=master
NEO_BLOCKCHAIN_COMMIT=a9f46bc7d351933e7d8666665c49f850ed5d8e24
NEO_PLUGINS_URL=https://github.com/neo-project/neo-plugins.git
NEO_PLUGINS_BRANCH=master
NEO_PLUGINS_COMMIT=3774004b6a4bb45034458fd90698079640f6079e

LOCAL_NEO_CLI_BLOCKCHAIN="false"
LOCAL_NEO_CLI_BLOCKCHAIN_URL="localfiles/neo-cli"
LOCAL_NEO_BLOCKCHAIN="false"
LOCAL_NEO_BLOCKCHAIN_URL="localfiles/neo"
LOCAL_NEO_PLUGINS="false"
LOCAL_NEO_PLUGINS_URL="localfiles/neo-plugins"

SET_NEO_VM="true"
NEO_VM_URL=https://github.com/neo-project/neo-vm.git
NEO_VM_BRANCH=master
NEO_VM_COMMIT=332db08ada15916e69451fc9a23075574ac511a1

LOCAL_NEO_VM="false"
LOCAL_NEO_VM_URL="localfiles/neo-vm"

PLUGINS_LIST="
ApplicationLogs
CoreMetrics
ImportBlocks
RpcNep5Tracker
RpcSecurity
RpcWallet
SimplePolicy
StatesDumper
"
```

**Comment by shargon** [comment]
Travis have errors too

**Comment by erikzhang** [comment]
I have no compilation errors here.

**Comment by shargon** [comment]
Now i haven't got compilation errors .... but the unit test still with errors

**Comment by superboyiii** [comment]
Start consensus failed!
image

**Comment by vncoelho** [comment]
Hi @superboyiii, you are ahead of us! ahueahuea
That is great that you are already testing.

Let's check it out. We need to double check the logic for simple policy and all initialization, the plugin might be not needed anymore.

**Comment by erikzhang** [comment]
image

There is no problem starting the consensus here. Have you modified the protocol.json and emptied the old Chain directory? @superboyiii

**Comment by erikzhang** [comment]
Fixed

**Comment by superboyiii** [comment]
Cool! Works well now. Good fix!
image

**Comment by superboyiii** [comment]
Cool! Works well now. Good fix!
image

**Comment by superboyiii** [comment]
"IsLowPriority"  need to be removed in SimplePolicy since Transcation.get_IsLowPrioriy() has been removed.

image

[neo-plugins#109](https://github.com/neo-project/neo-plugins/issues/109)

**Comment by vncoelho** [comment]
@superboyiii, you are right.
I think that maybe it is better to abolish the simplepolicy, I am not sure yet.
https://github.com/neo-project/neo/issues/963

**Comment by superboyiii** [comment]
A conflict comes out in Neo3.0.0-CI00130 if an external node makes transaction via a wallet which is opened by consensus node at the same time. 
(neo#970)[https://github.com/neo-project/neo/issues/970#issue-474952213]

**Pull request merged**
