### PR TITLE
Printint error message when "UnlockWallet" wallet is not found

### LINKED ISSUE #471: An non-existent wallet which is set to config.json, but neo-cli doesn't throw any exception while start and open wallet automatically.
An not existed wallet which is set to config.json, but neo-cli doesn't throw any exception while start and open wallet automatically. 
For example, set the **path** in  **UnlockWallet** to an non-existent wallet.
image
Then I start neo-cli.
image
Then input "show state" command.
image
The "Index height" appears!!! It's too weird!

### PR DESCRIPTION
**Pull request by lock9**
Closes #471

### CODE REVIEW

**Comment by lock9** [comment]
@shargon that is a different error. When you use a wrong password, the message appears, it just doesn't appear when you are using a wallet that doesn't exist.

**Comment by lock9** [comment]
@shargon  any questions?

**Comment by shargon** [comment]
> When you use a wrong password, the message appears, it just doesn't appear when you are using a wallet that doesn't exist.

Yes as you said, is printed here 

https://github.com/neo-project/neo-cli/blob/7a7d961fbfa04a039c871311e1b35d82827c2451/neo-cli/Shell/MainService.cs#L825

We should unify the messages, you don't think so?

**Comment by lock9** [comment]
@shargon  I think they are different, one is a startup function, the other is user drive command. I think it is ok the way it is, but let's wait for a second approval.

**Comment by nicolegys** [comment]
Tested
image
@lock9

**Pull request merged**
