### PR TITLE
Add getwalletheight RPC call

### PR DESCRIPTION
**Pull request by DaveWK**
This adds a RPC call to retrieve the wallet height. This helps with understanding if the wallet has caught up to the block height.

It returns 400 Access denied if a wallet is not loaded in the same way as other RPC calls.

### CODE REVIEW

**Comment by DaveWK** [comment]
@erikzhang should I put this against the neo 3.0 repo instead? this is critical for knowing what height the balance returned by getbalance is.

**Comment by erikzhang** [comment]
> should I put this against the neo 3.0 repo instead?

Yes, please.

**Comment by DaveWK** [comment]
It looks like the 3.0 repo you've removed the wallet-related rpc from neo-cli, and the wallet loading functionality doesn't exist in the /neo/ repo; which should this code live in?

**Comment by DaveWK** [comment]
@erikzhang can this be merged? this really makes it impossible to know if the balance reported is the balance at a particular height..

**Pull request merged**
